version: '2'
services:
    greenhear-app:
        image: greenhear
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://greenhear-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=greenhear
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    greenhear-mongodb:
        extends:
            file: mongodb.yml
            service: greenhear-mongodb
